### ISSUE TITLE
As an impatient chess player, I want chess games to end quick, so I want a lose page at the end of the turn when the timer runs out.

### ISSUE THREAD

**Issue by workaholic101** [UB-CSE/course-project-cheakmate#100]
Acceptance Test: 

- Go to https://cse442-test4.herokuapp.com/game.html
- Make the timer of either white or black chess piece player turn become 0:00. 
- The losing page should appear when the timer of either player becomes 0:00.

**Comment by Intesar-Alam** [comment]
The current timer should be 2:00
